items = [{"item" : "Crystal Ring Shield", "description" : "Soul of Moonlight Butterfly and +10 shield."},
{"item" : "Moonlight Butterfly Horn", "description" : "Soul of Moonlight Butterfly and +10 spear or +10 thrusting sword."},
{"item" : "Chaos Blade", "description" : "Soul of Quelaag and +10 Katana."},
{"item" : "Quelaag's Furysword", "description" : "Soul of Quelaag and +10 curved sword."},
{"item" : "Greatsword of Artorias", "description" : "Soul of Sif and +10 broken straight sword or +10 straight sword hilt."},
{"item" : "Greatsword of Artorias (cursed)", "description" : "Soul of Sif and +10 dagger or +10 greatsword or +10 straightsword."},
{"item" : "Greatshield of Artorias", "description" : "Soul of Sif and +10 shield."},
{"item" : "Dragon Bone Fist", "description" : "Core of an Iron Golem and +10 caestus or +10 claw."},
{"item" : "Golem Axe", "description" : "Core of an Iron Golem and +10 axe."},
{"item" : "LifeHunt Scythe", "description" : "Soul of Priscilla and +10 halberd or +10 whip."},
{"item" : "Dragonslayer Spear", "description" : "Soul of Ornstein and +10 spear or +10 thrusting sword. Note: kill Smough first."},
{"item" : "Smough's Hammer", "description" : "Soul of Smough and +10 hammer or +10 great hammer. Note: kill Ornstein first."},
{"item" : "Darkmoon Bow", "description" : "Soul of Gwyndolin and +10 bow."},
{"item" : "Tin Darkmoon Catalyst", "description" : "Soul of Gwyndolin and catalyst."},
{"item" : "Great Lord Greatsword", "description" : "Soul of Gwyn, Lord of Cinder and +10 dagger or +10 greatsword or +10 straight sword."},
{"item" : "Drake Sword", "description" : "Cut the tail off the dragon at undead burg. May be able to get it off by shooting arrows under the bridge."},
{"item" : "Dragon King Greataxe", "description" : "Cut the tail of Gaping Dragon (Depths boss)."},
{"item" : "Priscilla's Dagger", "description" : "Cut Priscilla's tail off."},
{"item" : "Moonlight Greatsword", "description" : "Cut the tail off Seath the Scaleless."},
{"item" : "Dragon Greatsword", "description" : "Cut the tail off of the Stone Dragon (at Ash Lake)."},
{"item" : "Gravelord Sword", "description" : "Join the Gravelord Servant Covenant. In the catacombs there is a row of coffins with a titanite demon at the end. There is one before waking it up that has an open lid. You must go in, wait 30 seconds, and possess an eye of death. You will be transported and you have to pray to Sarcophagus Gravelord."},
{"item" : "Dark Hand", "description" : "Join the Darkwraith Covenant. To join, do not place the lord vessal for the serpant at firelink shrine, instead, defeat the four kings and another serpant will appear and allow you to join the covenant."},
{"item" : "Crescent Axe", "description" : "Sold by Patches (dude in tomb of the giants) after defeating Nito."},
{"item" : "Demon's Catalyst", "description" : "Drop from Demon Firesage in Demon Ruins."},
{"item" : "Izalith Catalyst", "description" : "Drop from Daughter of Choas in Lost Izalith."},
{"item" : "Crest Shield", "description" : "Dropped by Oscar, Knight of Astora on your return visit to Undead Asylum."},
{"item" : "Grant", "description" : "Defeat the phantom Paladin Leeroy on your way to face Nito. The phantom is by the waterfall. You must not be hallow and have placed the lordvessal. Don't knock him off the ledge."},
{"item" : "Sanctus", "description" : "Defeat the phantom Paladin Leeroy on your way to face Nito. The phantom is by the waterfall. You must not be hallow and have placed the lordvessal. Don't knock him off the ledge."},
{"item" : "Black Knight Sword", "description" : "Possible drop from black knight wielding it at Undead Burg, Undead Asylum, and Kiln of the First Flame."},
{"item" : "Black Knight Greatsword", "description" : "Possible drop from black knight wielding it at Undead Parish and Kiln of the First Flame."},
{"item" : "Black Knight Greataxe", "description" : "Possible drop from black knight wielding it at The Catacombs and Kiln of the First Flame."},
{"item" : "Black Knight Halberd", "description" : "Possible drop from black knight wielding it at Darkroot Basin, Tomb of the Giants, and Kiln of the First Flame."},
{"item" : "Black Knight Shield", "description" : "Possible drop from any black knight."},
{"item" : "Silver Knight Straight Sword", "description" : "Possible drop from Silver Knight wielding it at Anor Londo."},
{"item" : "Silver Knight Spear", "description" : "Possible Drop from Silver Knight wielding it at Anor Londo."},
{"item" : "Silver Knight Shield", "description" : "Any Silver Knight at Anor Londo."},
{"item" : "Channeler's Trident", "description" : "Channeler's are those dancing spear magic guys. If they didn't drop at Undead Parish or Depths then you may as well farm the respawning ones at The Duke's Archives."},
{"item" : "Giant's Halberd", "description" : "Dropped by Sentinals at Anor Londo. Also sold by the giant Blacksmith."},
{"item" : "Stone Greatsword", "description" : "Dropped by Stone Knight in Darkroot Garden. Also sold by Shiva of the East after joining the Forest Hunter Covenant, speaking to him, and paying a visit by the elevator at the bottom of Blighttown."},
{"item" : "Stone GreatShield", "description" : "Dropped by Stone Knight in Darkroot Garden."},
{"item" : "Effigy Shield", "description" : "Found on a corpse guarded by a black knight in Tomb of the Giants between the first and second bonfire."},
{"item" : "Bloodshield", "description" : "Found on a corpse in the Painted World of Ariamis on the bridge near the undead dragon."},
{"item" : "Velka's Rapier", "description" : "Found on a corpse in the Painted World of Ariamis on a corpse after the door that opens with the annex key. Break some wooden planks."},
{"item" : "Black Iron Greatshield", "description" : "In Anor Londo before the giant painting there is a corpse on the left."},
{"item" : "Dragonslayer Greatbow", "description" : "On a roof in Anor Londo near the Giant Blacksmith. Go through the broken window on the upper levels."},
{"item" : "Dragon Tooth", "description" : "Found in a basement area behind an illusory wall in Anor Londo after the third bonfire. Watch out for the mimic."},
{"item" : "Havel's Greatshield.", "description" : "Found in a basement area behind an illusory wall in Anor Londo after the third bonfire. Watch out for the mimic."},
{"item" : "Astora's Straight Sword", "description" : "Found on a corpse near the undead dragon in Valley of Drakes. It has a divine effect btw."},
{"item" : "Dragon Crest Shield", "description" : "Found on a corpse near the undead dragon in Valley of Drakes."}
];