items = [{"item" : "Heal", "description" : "Purchase from Petrus of Thorolund or Reah."},
{"item" : "Great Heal Excerpt", "description" : "Purchase from Petrus of Thorolund or Reah."},
{"item" : "Homeward", "description" : "Purchase from Petrus of Thorolund or Reah."},
{"item" : "Force", "description" : "Purchase from Petrus of Thorolund or Reah."},
{"item" : "Great Heal", "description" : "Purchase from Reah."},
{"item" : "Wrath of God's", "description" : "Purchase from Reah."},
{"item" : "Seek Guidance", "description" : "Purchase from Reah."},
{"item" : "Magic Barrier", "description" : "Purchase from Reah."},
{"item" : "Replenishment", "description" : "Reward from killing Reah's hollowed body guards in Tomb of the Giants."},
{"item" : "Karmic Justice", "description" : "Sold by the dude after going down from ringing the bell of awakening in the Undead Parish."},
{"item" : "Gravelord Sword Dance", "description" : "Join the gravelord covenant. Can be access by praying to Nito after you have the eye of death and going in a tomb in the room with a row of coffins and a titanite demon in the catacombs."},
{"item" : "Gravelord Greatsword Dance", "description" : "Gain rank 1 in Gravelord Servant Covenant. See Gravelord Sword Dance above for joining information."},
{"item" : "Darkmoon Blade Miracle", "description" : "Reward for getting +1 in Gwyndolin's covenant. You can join by either killing Gwynevere or equiping the Darkmoon Seance Ring and going to the Darkmoon Tomb. There will be a staircase and you can kneel before the white fog. You will need 10 Souvenir of Reprisal to gain rank 1."},
{"item" : "Sunlight Blade", "description" : "Found in a chest after defeating Gwyndolin"},
{"item" : "Lightning Spear", "description" : "Given as a bonus for joining the Warrior of Sunlight Covenant. You need 25 faith or less if you helped kill bosses as a white phantom."},
{"item" : "Great Lightning Spear", "description" : "Rewarded for getting rank 1 in the Warrior of Sunlight covenant (required 10 Sunlight Medals)."},
{"item" : "Sunlight Spear", "description" : "Reach rank 1 in the Warrior of Sunlight covenant (requires 10 Sunlight Medals) and offer Lord Gwyn's soul."},
{"item" : "Emit Force", "description" : "Help Onion Bro by changing the direction of the boulders in Sen's Fortress and killing the Silver Knights in Anor Londo. After that then you speak to him in Firelink Shrine and tell him you did the stuff."},
{"item" : "Soothing Sunlight", "description" : "Dropped by a Pisaca in the base of the prison in the Duke's Archives"},
{"item" : "Bountiful Sunlight", "description" : "Dropped by a Pisaca in the base of the prison in the Duke's Archives"},
{"item" : "Great Magic Barrier", "description" : "In Ash Lake, make your way to the other side of the second tree and climb the branch leading around it. Below this branch on the right side of it, there will be a broken log which is actually a tunnel. Drop into the tunnel and find the miracle."},
{"item" : "Tranqual Walk of Peace", "description" : "Found on a corpse in the Catacomb's upper floor. There will be a ladder that goes to a small room with the miracle."},
{"item" : "Vow of Silence", "description" : "In the Painted World of Ariamis on top of the tower that requires the Annex Key to Access. There will be some crow demons that will ambush you."}
];