items = [{"item" : "Fireball", "description" : "Purchase from Laurentius or Quelana of Izalith."},
{"item" : "Fire Orb", "description" : "Purchase from Laurentius or Quelana of Izalith."},
{"item" : "Combustion", "description" : "Purchase from Laurentius or Quelana of Izalith."},
{"item" : "Iron Flesh", "description" : "Purchase from Laurentius."},
{"item" : "Flash Sweat", "description" : "Purchase from Laurentius."},
{"item" : "Poisen Mist", "description" : "Sold by Eingyi. You must be infected by an egg on your head. Also found on the way to the Hollows."},
{"item" : "Toxic Mist", "description" : "Sold by Eingyi. You must be infected by an egg on your head."},
{"item" : "Great Chaos Fireball", "description" : "Gift for joining the Daughter of Chaos covenant. It is in a hidden room bellow the second bell."},
{"item" : "Chaos Storm", "description" : "Reach rank 2 in the Daughter of Chaos covenant (hidden bellow the second bell). Requires 30 humanity."},
{"item" : "Great Fireball", "description" : "Sold by Quelana of Izalith."},
{"item" : "Firestorm", "description" : "Sold by Quelana of Izalith."},
{"item" : "Fire Whip", "description" : "Sold by Quelana of Izalith."},
{"item" : "Great Combustion", "description" : "Sold by Quelana of Izalith."},
{"item" : "Undead Rapport", "description" : "Sold by Quelana of Izalith."},
{"item" : "Fire Tempest", "description" : "After buying her stuff, she wants you to do her a favour and kill her mother and sister. Defeat the bed of chaos and return to her. Or you could just kill her after buying everything."},
{"item" : "Chaos Fire Whip", "description" : "Found in a chest on the right before going down to fight the boss in Lost Izalith."},
{"item" : "Fire Surge", "description" : "In the skeleton area in painted world, there will be an invisable wall. Pass it, go up some steps, and kill a toxic hollow guy."},
{"item" : "Acid Surge", "description" : "Found on corpse in Painted World."},
{"item" : "Power Within", "description" : "Found on a corpse in blight town under a big parasite."}
];