items = [{"item" : "Soul Arrow", "description" : "Purchase from Griggs of Vinheim or Big Hat Logan."},
{"item" : "Great Soul Arrow", "description" : "Purchase from Griggs of Vinheim or Big Hat Logan."},
{"item" : "Heavy Soul Arrow", "description" : "Purchase from Griggs of Vinheim or Big Hat Logan."},
{"item" : "Great Heavy Soul Arrow", "description" : "Purchase from Griggs of Vinheim or Big Hat Logan."},
{"item" : "Aural Decoy", "description" : "Purchase from Griggs of Vinheim."},
{"item" : "Fall Control", "description" : "Purchase from Griggs of Vinheim."},
{"item" : "Hush", "description" : "Dropped by Hollowed Griggs of Vinheim in Sen's Fortress. Also a available as a drop in Sen's Fortress. You take the boulder path that leads to the mimic, there is a gap in the wall on the right. Take out the serpant mage. Go down the hallway and there will be a cell."},
{"item" : "Homing Soulmass", "description" : "Purchase from Big Hat Logan."},
{"item" : "Homing Crystal Soulmass", "description" : "Purchase from Big Hat Logan after moving to to the Duke's Archives."},
{"item" : "Magic Weapon", "description" : "Purchase from Big Hat Logan or Griggs of Vinheim."},
{"item" : "Great Magic Weapon", "description" : "Purchase from Big Hat Logan or get in Anor Londo after cutting the chandelier down in the room with the painting and fetching it."},
{"item" : "Crystal Magic Weapon", "description" : "Purchase from Big Hat Logan or Griggs of Vinheim."},
{"item" : "Magic Shield", "description" : "Purchase from Big Hat Logan or Griggs of Vinheim."},
{"item" : "White Dragon Breath", "description" : "Kill hollowed Big Hat Logan."},
{"item" : "Hidden Weapon", "description" : "Purchase from Dusk of Oolocile."},
{"item" : "Hidden Body", "description" : "Purchase from Dusk of Oolocile."},
{"item" : "Cast Light", "description" : "Purchase from Dusk of Oolocile."},
{"item" : "Repair", "description" : "Purchase from Dusk of Oolocile."},
{"item" : "Chameleon", "description" : "Purchase from Dusk of Oolocile."},
{"item" : "Resist Curse", "description" : "Purchase from Ingward. He is on the rooftop in New Londo Ruins."},
{"item" : "Strong Magic Shield", "description" : "Found in Duke's Archives. Easy to find if your following Logan's questline."},
{"item" : "Remedy", "description" : "Found in a chest in Blighttown. It is on the upper section on a tree branch on the route to Valley of Drakes."}
];